(define (main)
  (if (> 12  2) 
      (display "This is true")
      (display "This is false")
      )
   (newline)
  (cond ((> 3 3) (display  "greater"))
      ((< 3 3) (display "less"))
      (else (display "equal"))) 
  (newline)
  (display "This is a test run")
  (newline)
  )

(main)
