// Autogenerated Scheme to C++ Code
// File: test.cpp
#include <iostream>
#include "Object.cpp"
using namespace std;

int main(){
if(Object(12)>Object(2)){
cout << Object("This is true"); 
}
else{
cout << Object("This is false"); 
}
cout << endl; 
if(Object(3)>Object(3)){ 
cout << Object("greater"); 
} 
else if(Object(3)<Object(3)){ 
cout << Object("less"); 
} 
else{ 
cout << Object("equal"); 
} 
cout << endl; 
cout << Object("This is a test run"); 
cout << endl; 
return 0;
}
