// Autogenerated Scheme to C++ Code
// File: test.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main(){
  if(12>2){
    cout << "This is true"; 
  }
  else{
    cout << "This is false"; 
  }
  cout << endl; 
  if(3>3){ 
    cout << "greater"; 
  } 
  else if(3<3){ 
    cout << "less"; 
  } 
  else{ 
    cout << "equal"; 
  } 
  cout << endl; 
  cout << "This is a test run"; 
  cout << endl; 
}
