(define (func1 v1 v2)
  (cons v1 v2)
  (car v1)
  )


(define (main)
  (if (> 12  2) 
      (display "This is true")
      (display "This is false")
      )
   (newline)
  (cond ((> 3 3) (display  "greater"))
      ((< 3 3) (display "less"))
      (else (display "equal"))) 
  (newline)
  (display "This is a test run")
  (newline)
  (display (- 12 (+ 5 6)))
  (newline)
  )

(main)
